# security:
#     # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
#     password_hashers:
#         Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

#     # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
#     providers:
#         users_in_memory: { memory: null }

#     firewalls:
#         dev:
#             # Ensure dev tools and static assets are always allowed
#             pattern: ^/(_profiler|_wdt|assets|build)/
#             security: false
#         main:
#             lazy: true
#             provider: users_in_memory

#             # Activate different ways to authenticate:
#             # https://symfony.com/doc/current/security.html#the-firewall

#             # https://symfony.com/doc/current/security/impersonating_user.html
#             # switch_user: true

#     # Note: Only the *first* matching rule is applied
#     access_control:
#         # - { path: ^/admin, roles: ROLE_ADMIN }
#         # - { path: ^/profile, roles: ROLE_USER }

# when@test:
#     security:
#         password_hashers:
#             # Password hashers are resource-intensive by design to ensure security.
#             # In tests, it's safe to reduce their cost to improve performance.
#             Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
#                 algorithm: auto
#                 cost: 4 # Lowest possible value for bcrypt
#                 time_cost: 3 # Lowest possible value for argon
#                 memory_cost: 10 # Lowest possible value for argon
security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                always_use_default_target_path: true
                enable_csrf: true
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/user/new, roles: PUBLIC_ACCESS }
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/user/new, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/responsable, roles: ROLE_RESPONSABLE_CLUB }
        - { path: ^/etudiant, roles: ROLE_ETUDIANT }
        - { path: ^/home, roles: ROLE_USER }

    role_hierarchy:
        ROLE_ADMIN: [ROLE_RESPONSABLE_CLUB, ROLE_ETUDIANT, ROLE_USER]
        ROLE_RESPONSABLE_CLUB: [ROLE_ETUDIANT, ROLE_USER]
        ROLE_ETUDIANT: [ROLE_USER]

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10